### ISSUE TITLE
GPG support?

### ISSUE THREAD

**Issue by pschwede** [r10s/deltachat-android#66]
Hi!

Currently, if Alice used GPG encryption e.g. using Enigmail, Bob cannot read the mail.

Do you see a way to add GPG support to DeltaChat?

**Comment by r10s** [comment]
Yeah! It's the most important thing I'm currently working on ...

Delta Chat 1.0 will have PGP/GPG support, see https://github.com/r10s/messenger-backend/issues/6

**Comment by zoff99** [comment]
that's good news. will it use OpenKeychain as provider?

**Comment by r10s** [comment]
The details are not yet clear, however, our focus is clearly to allow end-to-end-encryption for the users _without_ doing anything for it. 

Delta Chat to Delta Chat communication should be encrypted out-of-the-box.

**Comment by r10s** [comment]
Any further discussion should go to the core.
