### ISSUE TITLE
Do not more get messages :(

### ISSUE THREAD

**Issue by elvecio** [r10s/deltachat-android#71]
I'm not entirely sure, but since the last update, I can no longer receive the messages. Before worked very well ;-) , but in recent days I have not received anything, I can  send but I do not get messages, but if I enter my email I see people's responses, these responses simply do not arrive more in deltachat.
ps: (testing with AOL-mail)

**Comment by r10s** [comment]
Can you re-install the old version and try over?
Just to make sure, what the problem is.

**Comment by elvecio** [comment]
old version but ...nothing, always the same problem.
I begin to suspect that deltachat no longer receives messages from aol-mail, starting from saturday.
it is a pity, it was working really well.

**Comment by elvecio** [comment]
now works again ;-)
v.0.1.32
