### ISSUE TITLE
Keyboard not useable on Nexus 7 (2012)

### ISSUE THREAD

**Issue by endbacher** [r10s/deltachat-android#73]
While installation works without problem on Nexus 7 with AOSP 7.1.2 there is no initial setup possible. In text fields (for example email address or server) the keyboard scrolls in an immediately out again without being able to enter anything. This is independent from the keyboard app used.
Happy Easter!

**Comment by r10s** [comment]
Where did you get the download from? On https://download.lineageos.org I'll only find Downloads for the Nexus 7 from 2013.

**Comment by r10s** [comment]
Can you please test the following apk: https://getdelta.org/public/download/DeltaChat-0.1.30-fat-debug.apk (please use this apk only for testing as it won't get any updates)

**Comment by endbacher** [comment]
Hallo Björn,
FYI, LineageOS 14.1 build for grouper / tilapia is availabe only via XDA on this tread: https://forum.xda-developers.com/nexus-7/development/rom-android-7-aosp-grouper-t3467514
Don't think that it will find it's way to the official page anymore, devices are too old.

Good news is that your test build fixed the keyboard issue on my device (tested with several keyboard apps in portrait and landscape mode, all fine).

**Comment by r10s** [comment]
Perfect! Thank you very much for testing! Delta Chat 0.1.31 will support tables then.
