### ISSUE TITLE
Rename repo to deltachat-android

### ISSUE THREAD

**Issue by kskarthik** [r10s/deltachat-android#75]
`deltachat-android` name is apt for this repo :)

**Comment by r10s** [comment]
Or `delta-chat-android`? The name of the app is "Delta Chat", not "Deltachat" ...

**Comment by r10s** [comment]
However, renaming should be very easy and transparent as request with the old name are just redirected to the new one. This would help us with F-Droid etc., see https://help.github.com/articles/renaming-a-repository/

**Comment by kskarthik** [comment]
`deltachat-android` sounds better

**Comment by kskarthik** [comment]
> The name of the app is "Delta Chat", not "Deltachat" ...

How about `DeltaChat-android`

**Comment by r10s** [comment]
I will  go for deltachat-android, this was also my first idea.

**Comment by r10s** [comment]
Renamed, also the backend which is called deltachat-core now.
The old names should redirect to the new ones, so F-Droid etc. could be updated when there is some time left.

**Comment by kskarthik** [comment]
Repo Description could also be changed to "delta chat android client" would be SEO friendly ☺ same with other repos too appropriately

**Comment by kskarthik** [comment]
Back end frontend could be misunderstood as client/server stuff 🤔

**Comment by r10s** [comment]
Well, "Android Client" could also be misunderstand as if there is an "Android Server", however, I've updated the README, see https://github.com/r10s/deltachat-android/commit/c69e128e83433a904eb9903f92a936809094876f

Regarding the repository name: "Core" is clear and for the clients it might be the best to leave "Frontend" or "Client" completely out.

**Comment by kskarthik** [comment]
Perfect 👌
