### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by MauritsCornelis** [r10s/deltachat-android#78]
Here you are:

<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:tools="http://schemas.android.com/tools">
    <string name="AppName">Delta Chat</string>
    <string name="LanguageName">Español</string>
    <string name="LanguageNameInEnglish" tools:keep="@string/LanguageNameInEnglish">English</string>
    <string name="LanguageCode" tools:keep="@string/LanguageCode">en</string>
    
    <string name="Settings">Ajustes</string>
    <string name="NewGroup">Nuevo grupo</string>
    <string name="Yesterday">ayer</string>
    <string name="NoResult">Sin resultados</string>
    <string name="NoChats">Aún sin chats.</string>
    <string name="WaitingForNetwork">Esperando red…</string>
    <string name="Connecting">Conectando…</string>
    <string name="Updating">Actualizando…</string>
    <string name="DeleteChat">Eliminar chat</string>
    <string name="SelectChat">Elige el chat …</string>
    <string name="Search">Buscar</string>
    <string name="MuteNotifications">Silenciar notificaciones</string>
    <string name="MuteFor">Silenciado durante %1$s</string>
    <string name="UnmuteNotifications">No silenciar</string>
    <string name="Draft">Borrador</string>
    
    <string name="NoAudio">Por favor, añade archivos a la carpeta de música en tu dispositivo para verlos aquí.</string>
    <string name="AttachMusic">Música</string>
    
    <string name="SelectFile">Elegir archivo</string>
    <string name="FreeOfTotal">%1$s de %2$s libres</string>
    <string name="ErrorHint">Error desconocido</string>
    <string name="AccessError">Error de acceso</string>
    <string name="NoFiles">Aún sin archivos…</string>
    <string name="NotMounted">Almacenamiento no montado</string>
    <string name="UsbActive">Transferencia USB activa</string>
    <string name="InternalStorage">Almacenamiento Interno</string>
    <string name="ExternalStorage">Almacenamiento Externo</string>
    <string name="SystemRoot">Raíz del Sistema</string>
    <string name="SdCard">Tarjeta SD</string>
    <string name="Folder">Carpeta</string>
    <string name="GalleryInfo">Para enviar imágenes sin compresión</string>
    
    <string name="ChatGallery">Galería</string>
    <string name="ChatCamera">Cámara</string>
    <string name="NoMessages">Aún sin mensajes.</string>
    <string name="ForwardedMessage">Mensaje reenviado</string>
    <string name="From">De</string>
    <string name="NoRecent">No hay recientes</string>
    <string name="TypeMessage">Mensaje</string>
    <string name="SlideToCancel">DESLIZA PARA CANCELAR</string>
    <string name="SaveToDownloads">Guardar en descargas</string>
    <string name="DeleteGif">¿Eliminar GIF?</string>
    <string name="SaveToMusic">Guardar en música</string>
    <string name="Share">Compartir</string>
    <string name="SendItems">Enviar %1$s</string>
    <string name="ClearRecentEmoji">¿Borrar los emojis recientes?</string>
    <string name="AddShortcut">Añadir acceso directo</string>
    <string name="ShortcutAdded">Acceso directo añadido al escritorio</string>
    
    <string name="Reply">Responder</string>
    <string name="ReplyToGroup">Responder a %1$s</string>
    <string name="ReplyToContact">Responder a %1$s</string>
    
    <string name="NoContacts">Aún sin contactos</string>
    <string name="TodayAt">a las</string>
    <string name="YesterdayAt">ayer a las</string>
    
    <string name="SendMessageTo">Invitar a…</string>
    <string name="EnterGroupNamePlaceholder">Nombre del grupo</string>
    
    <string name="SharedMedia">Multimedia</string>
    <string name="AddMember">Añadir miembro</string>
    <string name="Notifications">Notificaciones</string>
    <string name="RemoveMember">Eliminar del grupo</string>
    
    <string name="NewContactTitle">Añadir contacto</string>
    <string name="BlockContact">Bloquear</string>
    <string name="DeleteContact">Eliminar</string>
    <string name="Info">Información</string>
    
    <string name="Stickers">Stickers</string>
    <string name="AddStickers">Añadir stickers</string>
    <string name="AddToStickers">Añadir a stickers</string>
    <string name="StickersRemove">Eliminar</string>
    <string name="NoStickers">Sin stickers aún</string>
    
    <string name="TextSize">Tamaño del texto</string>
    <string name="EnableAnimations">Activar animaciones</string>
    <string name="UnblockContact">Desbloquear</string>
    <string name="NoBlocked">Sin usuarios bloqueados</string>
    <string name="DefaultForNormalMessages">Notificación de mensajes</string>
    <string name="Alert">Alerta</string>
    <string name="MessagePreview">Vista previa del mensaje</string>
    <string name="DefaultForGroupMessages">Notificaciones de grupo</string>
    <string name="Sound">Sonido</string>
    <string name="InAppNotifications">Notificaciones en la app</string>
    <string name="Vibrate">Vibraciones</string>
    <string name="Reset">Restablecer</string>
    <string name="ResetAllNotifications">Restablecer las notificaciones</string>
    <string name="NotificationsAndSounds">Notificaciones y sonidos</string>
    <string name="BlockedContacts">Usuarios bloqueados</string>
    <string name="Default">Por defecto</string>
    <string name="OnlyIfSilent">Sólo si está silenciado</string>
    <string name="ChatBackground">Fondo de chat</string>
    <string name="SendByEnter">Enviar con “Intro”</string>
    <string name="Language">Idioma</string>
    <string name="Help">Preguntas frecuentes</string>
    <string name="Enabled">Activadas</string>
    <string name="Disabled">Desactivadas</string>
    <string name="NotificationsService">Servicio keep-alive</string>
    <string name="NotificationsServiceInfo">Vuelve a abrir la app cuando el usuario o el sistema la cierra. Esto garantiza que la app pueda mostrar notificaciones.</string>
    <string name="NotificationsServiceConnection">Conexión en segundo plano</string>
    <string name="NotificationsServiceConnectionInfo">Conexión de bajo impacto, en segundo plano, para recibir notificaciones. Úsala para tener notificaciones fiables.</string>
    <string name="LedColor">Color del LED</string>
    <string name="BadgeNumber">Globo en el ícono</string>
    <string name="Short">Cortas</string>
    <string name="Long">Largas</string>
    <string name="RaiseToSpeak">Elevar para hablar</string>
    <string name="EditName">Editar nombre</string>
    <string name="NotificationsPriority">Prioridad</string>
    <string name="NotificationsPriorityDefault">Por defecto</string>
    <string name="NotificationsPriorityHigh">Alta</string>
    <string name="NotificationsPriorityMax">Máxima</string>
    <string name="RepeatNotifications">Repetir notificaciones</string>
    <string name="NotificationsOther">Otras</string>
    <string name="InChatSound">Sonidos en el chat</string>
    <string name="SmartNotifications">Notificaciones inteligentes</string>
    <string name="SmartNotificationsInfo">Sonar como máximo %1$s en %2$s</string>
    <string name="SmartNotificationsSoundAtMost">Sonar como máximo</string>
    <string name="SmartNotificationsTimes">veces</string>
    <string name="SmartNotificationsWithin">en</string>
    <string name="SmartNotificationsMinutes">minutos</string>
    <string name="DirectShare">Direct Share</string>
    <string name="DirectShareInfo">Mostrar los chats recientes al compartir</string>
    
    <string name="CacheSettings">Ajustes de caché</string>
    <string name="LocalDatabase">Base de datos local</string>
    <string name="LocalDatabaseClear">¿Borrar los mensajes en la caché?</string>
    <string name="LocalDatabaseInfo">Al borrar la base de datos se eliminarán los mensajes en la caché y se comprimirá la base de datos para liberar espacio de almacenamiento. Delta Chat requiere algunos datos para funcionar, así que la base de datos nunca podrá llegar a cero.\n
  \n
  Esto puede tardar algunos minutos.</string>
    <string name="ClearMediaCache">Borrar caché</string>
    <string name="CacheClear">Borrar</string>
    <string name="LocalCache">Otros archivos</string>
    <string name="CacheEmpty">Vacío</string>
    <string name="KeepMedia">Conservar multimedia</string>
    <string name="KeepMediaInfo">Las fotos, los vídeos y los archivos de los chats en la nube a los que <b>no accedas</b> durante ese periodo de tiempo se eliminarán del dispositivo para liberar espacio.</string>
    <string name="KeepMediaForever">Siempre</string>
    
    <string name="Passcode">Código de acceso</string>
    <string name="ChangePasscode">Cambiar código de acceso</string>
    <string name="ChangePasscodeInfo">Cuando configuras un código, aparece un candado en la pantalla de chats. Toca sobre él para bloquear y desbloquear la aplicación.\n
  \n
  Nota: si olvidas el código, tendrás que eliminar y reinstalar la aplicación.</string>
    <string name="PasscodePIN">PIN</string>
    <string name="PasscodePassword">Contraseña</string>
    <string name="EnterCurrentPasscode">Pon tu código de acceso actual</string>
    <string name="EnterNewFirstPasscode">Pon un código de acceso</string>
    <string name="EnterNewPasscode">Pon tu nuevo código de acceso</string>
    <string name="EnterYourPasscode">Pon tu código de acceso</string>
    <string name="ReEnterYourPasscode">Pon, otra vez, tu nuevo código</string>
    <string name="PasscodeDoNotMatch">Los códigos de acceso no coinciden</string>
    <string name="AutoLock">Bloqueo automático</string>
    <string name="AutoLockInfo">El bloqueo se activará transcurrido este tiempo.</string>
    <string name="AutoLockInTime">en %1$s</string>
    <string name="UnlockFingerprint">Desbloquear con la huella digital</string>
    <string name="FingerprintInfo">Confirma la huella digital para continuar</string>
    <string name="FingerprintNotRecognized">Huella digital no reconocida. Reinténtalo</string>
    
    <string name="SaveToGallery">Guardar en galería</string>
    <string name="Of">%1$d de %2$d</string>
    <string name="Gallery">Galería</string>
    <string name="AllPhotos">Todas las fotos</string>
    <string name="AllVideo">Todos los vídeos</string>
    <string name="NoPhotos">Aún sin fotos</string>
    <string name="NoVideo">Sin vídeos aún</string>
    <string name="CropImage">Recortar imagen</string>
    <string name="EditImage">Editar imagen</string>
    <string name="Enhance">Realzar</string>
    <string name="Highlights">Iluminación</string>
    <string name="Contrast">Contraste</string>
    <string name="Exposure">Exposición</string>
    <string name="Warmth">Temperatura</string>
    <string name="Saturation">Saturación</string>
    <string name="Vignette">Viñeta</string>
    <string name="Shadows">Sombras</string>
    <string name="Grain">Grano</string>
    <string name="Sharpen">Nitidez</string>
    <string name="Fade">Desvanecer</string>
    <string name="Tint">Matiz</string>
    <string name="TintShadows">SOMBRAS</string>
    <string name="TintHighlights">ILUMINACIÓN</string>
    <string name="Curves">Curvas</string>
    <string name="CurvesAll">TODO</string>
    <string name="CurvesRed">ROJO</string>
    <string name="CurvesGreen">VERDE</string>
    <string name="CurvesBlue">AZUL</string>
    <string name="Blur">Desenfoque</string>
    <string name="BlurOff">Apagado</string>
    <string name="BlurLinear">Lineal</string>
    <string name="BlurRadial">Radial</string>
    <string name="DiscardChanges">¿Descartar cambios?</string>
    <string name="ClearSearch">¿Quieres borrar el historial de búsqueda?</string>
    <string name="ClearButton">Borrar</string>
    <string name="PickerPhotos">Fotos</string>
    <string name="PickerVideo">Vídeo</string>
    <string name="AddCaption">Añadir un comentario…</string>
    <string name="PhotoCaption">Comentario de foto</string>
    <string name="VideoCaption">Comentario de vídeo</string>
    <string name="Caption">Comentario</string>
    
    <string name="PrivacySettings">Privacidad y seguridad</string>
    <string name="PrivacyTitle" tools:keep="@string/PrivacyTitle">Privacy</string>
    <string name="SecurityTitle">Seguridad</string>
    
    <string name="SendVideo">Enviar vídeo</string>
    <string name="OriginalVideo">Vídeo original</string>
    <string name="EditedVideo">Vídeo editado</string>
    <string name="CompressVideo">Comprimir Vídeo</string>
    
    <string name="Next">Siguiente</string>
    <string name="Back">Atrás</string>
    <string name="Done">Hecho</string>
    <string name="Open">Abrir</string>
    <string name="Save">Guardar</string>
    <string name="Cancel">Cancelar</string>
    <string name="Close">Cerrar</string>
    <string name="Add">Añadir</string>
    <string name="Edit">Editar</string>
    <string name="Send">Enviar</string>
    <string name="CopyToClipboard">Copiar</string>
    <string name="Delete">Eliminar</string>
    <string name="Forward">Reenviar</string>
    <string name="Retry">Reintentar</string>
    <string name="FromCamera">Desde la cámara</string>
    <string name="FromGalley">Desde la galería</string>
    <string name="Set">OK</string>
    <string name="OK">OK</string>
    <string name="Crop">RECORTAR</string>
    
    <string name="AttachPhoto">Foto</string>
    <string name="AttachVideo">Vídeo</string>
    <string name="AttachGif">GIF</string>
    <string name="AttachContact">Contacto</string>
    <string name="AttachDocument">Archivo</string>
    <string name="AttachSticker">Sticker</string>
    <string name="AttachVoiceMessage">Mensaje de voz</string>
    <string name="FromSelf">Tú</string>
    
    <string name="NoHandleAppInstalled">No tienes aplicaciones que puedan manejar el tipo de archivo “%1$s”. Por favor, instala una para continuar.</string>
    <string name="ContactAlreadyInGroup">Este usuario ya está en el grupo</string>
    <string name="ForwardMessagesTo">¿Reenviar mensajes a <b>%1$s</b>?</string>
    <string name="SendMessagesTo">¿Enviar mensajes a <b>%1$s</b>?</string>
    <string name="AreYouSureDeleteThisChat">¿Quieres eliminar este chat?</string>
    <string name="AreYouSureBlockContact">¿Quieres bloquear este contacto?</string>
    <string name="AreYouSureDeleteContact">¿Quieres eliminar este contacto?</string>
    
    <string name="PermissionContacts">Delta Chat necesita el acceso a tus contactos, para que puedas comunicarte con ellos en todos tus dispositivos.</string>
    <string name="PermissionStorage">Delta Chat necesita acceso a tu almacenamiento, para que puedas enviar y guardar fotos, vídeos, música y otros archivos.</string>
    <string name="PermissionNoAudio">Delta Chat necesita acceso a tu micrófono, para que puedas enviar mensajes de voz.</string>

    
    <string name="PermissionBattery">Delta Chat necesita estar conectado al fondo para recibir mensajes desde su servidor.\n
 \n
 Esto es un comportamiento normal, sin excesivo consumo batería que, no obstante, suele bloquearse por los optimizadores de batería.\n
 \n
 ¿Quiere adaptar los ajustes?</string>

    <string name="PermissionOpenSettings">Ajustes</string>
    
    <string name="Intro1Headline">Delta Chat</string>
    <string name="Intro1Message">La mensajería de <b>mayor alcance</b> del mundo. <b>Libre</b> y <b>segura</b>.</string>

    <string name="Intro2Headline">Independiente</string>
    <string name="Intro2Message"><b>Sin dependencia</b> de ordenadores o servidores ajenos. Usa solo tu servidor de correo.</string>

    <string name="Intro3Headline">Rápido</string>
    <string name="Intro3Message"><b>Mensajes automáticos</b> en segundos.<br/>Interfaz rápida.</string>

    <string name="Intro4Headline">Potente</string>
    <string name="Intro4Message">Conversaciones, imágenes, vídeos, audiomensajes <b>ilimitados</b> y más. Capacidad multicliente</string>

    <string name="Intro5Headline">Libre</string>
    <string name="Intro5Message"><b>Delta Chat</b> será siempre libre.<br/>Fuente abierta. Sin anuncios. Sin suscripción. Sin atarse a un proveedor.</string>

    <string name="Intro6Headline">Seguro</string>
    <string name="Intro6Message"><b>Cifrado</b> con algoritmos conocidos. Los mensajes permanecen en tus servidores.</string>

    <string name="Intro7Headline">Confiable</string>

    <string name="IntroStartMessaging">Empieza a conversar</string>
    
    <plurals name="Members">
        <item quantity="one">%d miembro</item>
        <item quantity="other">%d miembros</item>
    </plurals>
    <plurals name="Contacts">
        <item quantity="one">Contacto %d</item>
        <item quantity="other">Cursos</item>
    </plurals>
    <plurals name="MeAndMembers">
        <item quantity="one">%d miembro y yo</item>
        <item quantity="other">%d miembros y yo</item>
    </plurals>
    <plurals name="NewMessages">
        <item quantity="one">%d nuevo mensaje</item>
        <item quantity="other">%d nuevos mensajes</item>
    </plurals>
    <plurals name="messages">
        <item quantity="one">%d mensaje</item>
        <item quantity="other">%d mensajes</item>
    </plurals>
    <plurals name="AreYouSureDeleteMessages">
        <item quantity="one">¿Borrar mensaje %d? El mensaje se borrará también del servidor.</item>
        <item quantity="other">%</item>
    </plurals>
    <plurals name="NewMessagesInChats">
        
        <item quantity="one">%1$s en%2$s conversación</item>
        <item quantity="other">%1$s en%2$s conversaciones</item>
    </plurals>
    <plurals name="Chats">
        <item quantity="one">Conversación %d</item>
        <item quantity="other">Fundaciones %d</item>
    </plurals>
    <plurals name="Minutes">
        <item quantity="one">%d minuto</item>
        <item quantity="other">%d minutos</item>
    </plurals>
    <plurals name="Hours">
        <item quantity="one">%d hora</item>
        <item quantity="other">%d horas</item>
    </plurals>
    <plurals name="Days">
        <item quantity="one">%d día</item>
        <item quantity="other">%d días</item>
    </plurals>
    <plurals name="Weeks">
        <item quantity="one">%d semana</item>
        <item quantity="other">%d semanas</item>
    </plurals>
    <plurals name="Months">
        <item quantity="one">%d mes</item>
        <item quantity="other">%d meses</item>
    </plurals>
    <plurals name="MaxNotifications">
        
        <item quantity="one">Máximo %1$d notificación con %2$d</item>
        <item quantity="other">Máximo %1$d notificaciones con %2$d</item>
    </plurals>
    
    <string name="formatterMonthYear">MMMM \'de\' yyyy</string>
    <string name="formatterMonth">dd \'de\' MMM</string>
    <string name="formatterYear">dd.MM.yyyy</string>
    <string name="chatDate">EEE, d \'de\' MMMM</string>
    <string name="chatFullDate">EEE, d \'de\' MMMM \'de\' yyyy</string>
    <string name="formatterWeek">EEE</string>
    <string name="formatterDay24H">HH:mm</string>
    <string name="formatterDay12H">h:mm a</string>
    <string name="formatDateAtTime">%1$s a las %2$s</string>
    <string name="AccountSettings">Ajustes de cuenta</string>
    <string name="MyAccount">Mi cuenta</string>
    <string name="Yes">Sí</string>
    <string name="No">No</string>
    <string name="MyName">Mi nombre</string>
    <string name="MyNameExplain">Su nombre se muestra a los receptores.\n
 \n
 Si no introduce un nombre aquí, los receptores solo verán su dirección de correo de los ajustes de cuenta.</string>
    <string name="MyEmailAddress">Mi dirección de correo</string>
    <string name="Password">Contraseña</string>
    <string name="SmtpPassword">Contraseña SMTP</string>
    <string name="FromAbove">De arriba</string>
    <string name="SmtpLoginname">Nombre de ingreso SMTP</string>
    <string name="SmtpPort">Puerto SMTP</string>
    <string name="Automatic">Automático</string>
    <string name="ImapServer">Servidor IMAP</string>
    <string name="ImapLoginname">Nombre de ingreso IMAP</string>
    <string name="SmtpServer">Servidor SMTP</string>
    <string name="ImapPort">Puerto IMAP</string>
    <string name="InboxHeadline">Bandeja de entrada</string>
    <string name="OutboxHeadline">Bandeja de salida</string>
    <string name="BasicSettings">Ajustes básicos</string>
    <string name="MyAccountExplain">Para proveedores conocidos de correo, los ajustes adicionales se determinan automáticamente.</string>
    <string name="MyAccountExplain2" >Algunas veces, <b>hay que habilitar IMAP</b> en la interfaz web del correo.\n
 \n
 En caso de problemas, consulte a su proveedor de correo o el de sus amigos.</string>
    <string name="AccountNotConfigured">Cuenta no configurada</string>
    <string name="AboutThisProgram">Sobre Delta Chat</string>
    <string name="NotSet">No establecido</string>
    <string name="NewChat">Nuevo chat</string>
    <string name="Deaddrop">Buzón</string>
    <string name="Media">Multimedia</string>
    <string name="DeaddropInChatlist">Mostrar buzón en la lista de conversaciones</string>
    <string name="MuteAlways">Siempre silenciado</string>
    <string name="AskStartChatWith">¿Iniciar una conversación con <b>%1$s</b>?</string>
    <string name="DeaddropHint">Haga clic en la flecha de réplica para comenzar una conversación.</string>
    <string name="NotYetImplemented">Esta función no está disponible o está incompleta.</string>
    <string name="DefaultStatusText">Enviado desde mi Delta Chat</string>
    <string name="Name" >Nombre</string>
    <string name="EmailAddress">Dirección de correo</string>
    <string name="CannotDeleteContact">No puede borrar contactos en uso. En su lugar, bloquee el contacto.</string>
    <string name="BadEmailAddress">Dirección de correo errónea.</string>
    <string name="ContactCreated">Contacto creado.</string>
    <string name="ViewProfile">Ver perfil</string>
    
    <string name="OneMoment">Un momento...</string>
    <string name="NoChatsHelp">Comience a enviar mensajes pulsando el botón de nueva conversación en la esquina inferior derecha o pulse el botón de menú para más opciones.</string>
    <string name="ConfiguringAccount">Configurando cuenta...</string>
    <string name="CannotConnect">No puede conectar. Revise la configuración, por favor.</string>
    <string name="Intro7Message"><b>Delta Chat</b> es seguro para usar en negocios, consumir y basado en estándares.</string>
    <string name="InviteMenuEntry">Invitar a amigos</string>
    <string name="InviteText">Estoy usando Delta Chat ahora - %1$s - puede escribirme a %2$s</string>
    <string name="AdvancedSettings">Ajustes avanzados</string>
    <string name="AskResetNotifications" >¿Reiniciar los ajustes de notificación y sonido de esta página y de sus contactos y grupos?</string>
    <string name="AttachFiles">Adjuntar archivos</string>
    <string name="ErrGroupNameEmpty">Introduzca un nombre para el grupo.</string>
    <string name="MsgNewGroupDraftHint">Escriba un primer mensaje para permitir a los demás participar en este grupo.\n
 \n
 • No importa si los miembros no usan Delta Chat.\n
 \n
 • El primer mensaje puede tardar un momento.</string>
    <string name="MsgNewGroupDraft">Hola, he creado el grupo \"%1$s\" para nosotros.</string>
    <string name="MsgGroupNameChanged">Nombre de grupo cambiado de \"%1$s\" a \"%2$s\".</string>
    <string name="MsgGroupImageChanged">Imagen de grupo cambiada.</string>
    <string name="MsgMemberAddedToGroup">Añadido miembro %1$s.</string>
    <string name="MsgMemberRemovedFromToGroup">Eliminado miembro %1$s.</string>
    <string name="AskAddMemberToGroup">¿Añadir a <b>%1$s</b> al grupo?</string>
    <string name="AskRemoveMemberFromGroup">¿Eliminar <b>%1$s</b> del grupo?</string>
    <string name="ErrSelfNotInGroup">Debe ser miembro del grupo para realizar esta acción.</string>
    <string name="MsgGroupLeft">Grupo abandonado.</string>
    <string name="NoMessagesHint">Enviar mensaje a <b>%1$s</b>:\n
 \n
 • No importa si <b>%2$s</b> no usa Delta Chat.\n
 \n
 • El primer mensaje puede tardar un momento.</string>
    <string name="SendNRcvReadReceipts">Recibir y enviar entradas leídas</string>
    <string name="E2EEncryption">Cifrado punto a punto</string>
    <string name="E2EManagePrivateKeys">Gestionar claves privadas</string>
    <string name="E2ECompareKeys">Comparar claves</string>
    <string name="ResetContactsKey">Reiniciar claves de contacto</string>
    <string name="ForwardToTitle">Elige el chat …</string>
    <string name="SelectContact">Elegir un contacto</string>
    <string name="DoneHint">Hecho.</string>
    <string name="FileNotFound">Archivo %1$s no encontrado.</string>
    <string name="Error">Error %1$s</string>
    <string name="NoNetwork">Red no disponible.</string>
    <string name="Audio">Sonido</string>
    <string name="PleaseCutVideoToMaxSize">Reduzca el tamaño del vídeo hasta un máximo de %1$s, por favor.</string>
    <string name="PermNotificationTitle">Delta Chat</string>
    <string name="PermNotificationText">Conexión en segundo plano habilitada</string>
    <string name="SettingsFor">Ajustes para %1$s</string>

</resources>

**Comment by r10s** [comment]
Gracias :-)

**Comment by r10s** [comment]
The updated translation will be available in Delta Chat 0.1.30 then, see https://github.com/r10s/deltachat-android/commit/73cf5105ddc4ffde6e819e4d285b7be801738453

**Comment by MauritsCornelis** [comment]
Thanks to you for tour work.

**Comment by r10s** [comment]
You're welcome!

**Comment by MauritsCornelis** [comment]
Great! :)
