### ISSUE TITLE
Self updating app mechanism 

### ISSUE THREAD

**Issue by kskarthik** [r10s/deltachat-android#79]
Why not provide an option for app to update itself when new version is available. Pulling apk directly from fdroid repo without need of fdroid app . I found some related code here https://stackoverflow.com/questions/15213211/update-an-android-app-without-google-play 

Could be a good user experience option 🙂

**Comment by rigid** [comment]
The process of securely retrieving and upgrading an apk is not trivial. Why should apps implement it on their own when it's already done by repository apps (play, f-droid etc)?

**Comment by kskarthik** [comment]
I mean to pull latest apk from fdroid & update automatically

**Comment by zoff99** [comment]
@rigid Signal also does it now

**Comment by kskarthik** [comment]
@r10s  what are your thoughts on this?

**Comment by stefan-niedermann** [comment]
> I mean to pull latest apk from fdroid & update automatically

This is definitely a issue of an app store. just imagine every single one of all the million apps out there would have to implement its own upfating mechanism!

As far as i know will the next major f-droid release bring a new interface and an auto update mechanism. i really can not imagine any use case when it would be necessairy that the app updates itself...?
maybe if one has not installed an app store? how many people will that be (why ever) and how many effort will it take to implement and maintain such a feature?

sorry, i really can not understand the cause of this issue. may i ask what exactly your use-case is?

**Comment by r10s** [comment]
> @r10s what are your thoughts on this?

Well, I do not have a strong opinion in this issue - but maybe I am not seeing the correct use-case.

IMHO, F-Droid does the job just fine - and is _very_ simple for me to use - add on tag, ready. One advantage of self-updating apps may be speed - F-Droid normally takes some days until a new beta is shipped. But this would require not using the APKs from F-Droid but use self-compiled ones - which are then incompatible to the F-Droid-ones - so you cannot switch between self-hosted-APKs and F-Droid-APKs.

Finally, as soon as we're 1.0, we'll also go to the Play Store, maybe others. I would then see F-Droid still as a testing channel - new Delta Chat features are pushed first to F-Droid :-)
