### ISSUE TITLE
Check camera on Nougat

### ISSUE THREAD

**Issue by r10s** [r10s/deltachat-android#86]

**Comment by kskarthik** [comment]
Not working. Tried reboot. No use.

**Comment by r10s** [comment]
The missing camera right is not the problem (in fact, it is not needed at all when just firing the intent ACTION_IMAGE_CAPTURE).

The problem seems to be the `file:`-url, see https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by r10s** [comment]
Should be fixed by https://github.com/r10s/deltachat-android/commit/bee770bd2e9249dec84a167f87b514883680bf68

I have no native nougat device here an the emulator does not record videos - can you please check if if video recording works using the following APK: https://b44t.com/temp/DeltaChat-0.1.35-fat-debug.apk (can be installed beside the F-Droid app, uses a completely separate data region)

**Comment by kskarthik** [comment]
It works !

**Comment by kskarthik** [comment]
Camera & video both work fine. Happy 😀

**Comment by r10s** [comment]
Great! Thank you for testing.
The update will be available on F-Droid in Delta Chat 0.1.36 then.

**Comment by kskarthik** [comment]
Rapid dev 😁

**Comment by r10s** [comment]
Only sometimes ...

**Comment by r10s** [comment]
NB: Please uninstall the apk from this site after testing; it won't receive any updates.

**Comment by kskarthik** [comment]
Done
