### ISSUE TITLE
autocrypt other android

### ISSUE THREAD

**Issue by blelop** [r10s/deltachat-android#95]
The linked autocrypt docs mention a K-9 autocrypt build.  I had hoped to find it on F-droid also.  Any idea where to grab APKs?

I understand this is out of scope for an issue tracker; I surrender.

**Comment by r10s** [comment]
I have no details about K-9-Autocrypt, but I'm on the Autocrypt meeting in Freiburg this weekend - maybe I get some more detailed information there.

For now, I close this issue.
